<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "svb_schachturniere"
 *
 * Auto generated by Extension Builder 2017-09-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'schachturniere',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sebastian During',
    'author_email' => 'sebastian.during@svbalingen.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
