services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SchachvereinBalingenEv\SvbSchachturniere\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
